- lots of refactoring and updates

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,104 +1,141 @@
 #!/usr/bin/env bash
 #
-#   Perform the transformation steps for this Heroku app.
+#   Perform transformation steps for this Heroku app.
+#
+#   usage: bin/compile /tmp/build /app/cache /app/env
 #
 #   Reference: https://devcenter.heroku.com/articles/buildpack-api
 
 #   Debugging.
-#set -x
+#DISABLED:set -x
 
 #   Fail on error.
 set -eo pipefail
 
-echo '-----> Starting bin/compile'
+#   Display a section header.
+function section() {
+    echo
+    echo "-----> $1"
+}
 
-#   Location of the app (root dir of git repo e.g. /app).
-BUILD_DIR=$1
-
-#   Location for build artifacts stored between builds.
-CACHE_DIR=$2
-
-#   Contains a file for each of the app's config variables.
-ENV_DIR=$3
-
+#   Indent output send to stdout.
 function indent() {
   sed -u 's/^/       /'
 }
 
-echo "BUILD_DIR: ${BUILD_DIR}" | indent
-echo "CACHE_DIR: ${CACHE_DIR}" | indent
-echo "ENV_DIR: ${ENV_DIR}" | indent
+#   Remove a directory tree.
+function rmtree() {
+    dir_name=$1
+    if [ -d "${dir_name}" ]; then
+        echo "WARNING: found an existing directory ${dir_name}, removing it"
+        rm -rf ${dir_name} | indent
+    fi | indent
+}
 
-CONDA_REQUIREMENTS_FILE="${BUILD_DIR}/environment.yml"
+section "running build"
+
+#   Script paths.
+BUILDPACK_BIN_DIR=$(cd $(dirname $0); pwd)
+BUILDPACK_ROOT_DIR=$(dirname ${BUILDPACK_BIN_DIR})
+
+#   Build path (directory contents will form the home directory on the deployed app).
+BUILD_DIR=$1
+
+#   Location for build artifacts (will be persisted between builds).
+CACHE_DIR=$2
+
+#   Directory containing a file for each of the app's configuration variables.
+ENV_DIR=$3
 
 function export_env_dir() {
     env_dir=$1
     if [ -d "$env_dir" ]; then
-        for name in $(ls $env_dir); do
+        for name in $(ls ${env_dir}); do
             echo "$name"
-            export "$name=$(cat $env_dir/$name)"
+            export "$name=$(cat ${env_dir}/${name})"
         done
     fi
 }
-#export_env_dir $ENV_DIR
+#   Introduce configuration settings to environment.
+#DISABLED:export_env_dir $ENV_DIR
 
-#   Paths.
-BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
-ROOT_DIR=$(dirname $BIN_DIR)
-VENDOR_DIR="${ROOT_DIR}/vendor"
-
-echo "BIN_DIR: ${BIN_DIR}" | indent
-echo "ROOT_DIR: ${ROOT_DIR}" | indent
-echo "VENDOR_DIR: ${VENDOR_DIR}" | indent
-
-if [ ! -s "$CONDA_REQUIREMENTS_FILE" ]; then
-    echo "conda requirements was empty"
-    exit 1
-fi | indent
-
+#   Configuration settings.
+VENDOR_DIR="${CACHE_DIR}/vendor"
 CONDA_INSTALLER="${VENDOR_DIR}/miniconda_linux-x86_64.sh"
-echo "CONDA_INSTALLER: ${CONDA_INSTALLER}" | indent
-
-if [ ! -f "$CONDA_INSTALLER" ]; then
-    echo "Conda installer not found!"
-    exit 1
-fi | indent
-
-echo "-----> Installing conda"
-
-APP_DIR='/app'
-CONDA_ROOT_DIR="${APP_DIR}/miniconda"
+APP_ROOT_DIR='/app'
+CONDA_ENV_SETUP_FILE="${BUILD_DIR}/environment.yml"
+CONDA_ROOT_DIR="${APP_ROOT_DIR}/miniconda"
 CONDA_BIN_DIR="${CONDA_ROOT_DIR}/bin"
-
-if [ -d "$CONDA_ROOT_DIR" ]; then
-    CWD=$(pwd)
-    cd $(dirname $CONDA_ROOT_DIR)
-    rm -rf miniconda
-    cd $CWD
-fi | indent
-
-bash ${VENDOR_DIR}/miniconda_linux-x86_64.sh -b -p ${CONDA_ROOT_DIR} 2>&1 | indent
-
-echo "checking for updates" | indent
-
-export PATH=${CONDA_BIN_DIR}:$PATH
-
-conda update conda --yes --quiet | indent
-
-CONDA_VERSION=$(conda -V 2>&1)
-echo "${CONDA_VERSION} installed" | indent
-
-ENV_NAME='singletrack'
+ENV_NAME='root'
 ENV_ROOT_DIR="${CONDA_ROOT_DIR}/envs/${ENV_NAME}"
 ENV_BIN_DIR="${ENV_ROOT_DIR}/bin"
 
-echo "-----> Creating environment '${ENV_NAME}'"
-conda env create --quiet --file $CONDA_REQUIREMENTS_FILE --name $ENV_NAME | indent
+#   Add conda to path.
+export PATH=${CONDA_BIN_DIR}:$PATH
 
-echo "-----> Clearing down conda cache"
-conda clean --yes --tarballs --index-cache --packages --source-cache
+#   Display configuration.
+echo
+echo "environment:"
+echo
+( set -o posix ; set ) | egrep '^.*_(DIR|FILE|NAME|INSTALLER)=' | indent
 
-echo "-----> Relocating conda to build directory"
-mv $CONDA_ROOT_DIR $BUILD_DIR
+#   Check requirements file.
+if [ ! -s "${CONDA_ENV_SETUP_FILE}" ]; then
+    echo "ERROR: ${CONDA_ENV_SETUP_FILE} is blank!"
+    exit 1
+fi | indent
+
+section "caching build tools"
+
+if [ ! -d "${VENDOR_DIR}" ]; then
+    echo "creating cache for third party installers"
+    mkdir -p ${VENDOR_DIR}
+fi | indent
+
+if [ ! -f "${CONDA_INSTALLER}" ]; then
+    echo "transferring conda installer to cache"
+    cp -Rv ${BUILDPACK_ROOT_DIR}/vendor/$(basename ${CONDA_INSTALLER}) ${VENDOR_DIR}
+fi | indent
+
+section "installing conda"
+
+if [ ! -d "$APP_ROOT_DIR" ]; then
+    echo "ERROR: application directory (/app) was not found!"
+    exit 1
+fi | indent
+
+rmtree ${CONDA_ROOT_DIR}
+
+bash ${CONDA_INSTALLER} -b -p ${CONDA_ROOT_DIR} 2>&1 | indent
+
+echo $(conda -V 2>&1)" installed" | indent
+
+section "checking for conda updates"
+
+#   Make sure conda is on the latest version available.
+conda update conda --yes --quiet | indent
+
+echo "updated to " $(conda -V 2>&1) | indent
+
+section "installing conda helper packages"
+
+#   Required to enable the 'conda clean' command.
+conda install --yes --quiet conda-build | indent
+
+section "installing packages into ${ENV_NAME} environment"
+
+conda env update --quiet --name ${ENV_NAME} --file ${CONDA_ENV_SETUP_FILE} | indent
+
+section "cleaning up conda caches"
+
+conda clean --yes --tarballs --index-cache --packages --source-cache | indent
+
+section "relocating conda directory to build area"
+
+rmtree "${BUILD_DIR}/miniconda"
+echo "moving built conda parent directory to build area"
+mv -v ${CONDA_ROOT_DIR} ${BUILD_DIR} | indent
 
 #${ENV_BIN_DIR}/python setup.py develop
+
+section "build completed"
